# 오타로 인해 잘못 생성된 버전
"""Added column to user model

Revision ID: 04af6c17c9f2
Revises: ba88ca615ba6
Create Date: 2021-11-18 11:30:28.582312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04af6c17c9f2'
down_revision = 'ba88ca615ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True, server_defualt=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
