"""update nullable

Revision ID: 7592ebde6af9
Revises: dba4a396d841
Create Date: 2021-11-18 16:53:22.419550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7592ebde6af9'
down_revision = 'dba4a396d841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'category',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('item', 'texture',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('item', 'standard_1',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('item', 'standard_2',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('item', 'standard_3',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('item', 'unit',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('item', 'purchase_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('item', 'selling_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('item', 'isMngmt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('item', 'note',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('item', 'sort_order',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('item', 'created_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'created_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('item', 'sort_order',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('item', 'note',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('item', 'isMngmt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('item', 'selling_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('item', 'purchase_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('item', 'unit',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('item', 'standard_3',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('item', 'standard_2',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('item', 'standard_1',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('item', 'texture',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('item', 'category',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
