"""Added Item

Revision ID: dba4a396d841
Revises: 16b0f6d94881
Create Date: 2021-11-18 16:13:19.215135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba4a396d841'
down_revision = '16b0f6d94881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=20), nullable=False),
    sa.Column('texture', sa.String(length=20), nullable=False),
    sa.Column('standard_1', sa.String(length=20), nullable=False),
    sa.Column('standard_2', sa.String(length=20), nullable=False),
    sa.Column('standard_3', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Integer(), nullable=False),
    sa.Column('isMngmt', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
