"""remake item table

Revision ID: e41697facc9b
Revises: d08a8af60e61
Create Date: 2021-11-18 17:08:58.846760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41697facc9b'
down_revision = 'd08a8af60e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('item_name', sa.String(length=20), nullable=False),
    sa.Column('texture', sa.String(length=20), nullable=True),
    sa.Column('standard_1', sa.String(length=20), nullable=True),
    sa.Column('standard_2', sa.String(length=20), nullable=True),
    sa.Column('standard_3', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('purchase_price', sa.Integer(), nullable=True),
    sa.Column('selling_price', sa.Integer(), nullable=True),
    sa.Column('isMngmnt', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
