"""Added partner table

Revision ID: f2872d4931b8
Revises: c2591f298635
Create Date: 2021-11-19 16:02:12.819440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2872d4931b8'
down_revision = 'c2591f298635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('co_name', sa.String(length=20), nullable=True),
    sa.Column('business_type', sa.String(length=20), nullable=True),
    sa.Column('co_type', sa.String(length=20), nullable=True),
    sa.Column('repre', sa.String(length=20), nullable=True),
    sa.Column('business_no', sa.String(length=20), nullable=True),
    sa.Column('person', sa.String(length=20), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('cellphone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('address1', sa.String(length=20), nullable=True),
    sa.Column('address2', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner')
    # ### end Alembic commands ###
